[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
ar = "x86_64-w64-mingw32-gcc-ar"
rustflags = ["-C", "link-args=-static -static-libgcc -static-libstdc++"]

[build]
rustflags = [
    "--remap-path-prefix",
    "/home/smartbox/.cargo/registry=/cargo",  # Hides dependency paths
    "--remap-path-prefix",
    ".=/src"                                  # Hides your source code paths
]
